<?php
// Automatically Generated by TestLink Installer - Sun, 15 Sep 24 00:46:06 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'root');
define('DB_PASS', 'pwd_root');
define('DB_HOST', '192.168.56.1');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
